In [30]:
# load dataset and show first rows 
# describe how many values it has -> 1 million rows
import pandas as pd
import numpy as np
pd.options.display.max_rows = 1000
full_dataset = pd.read_csv(r'card_transdata.csv')
display(full_dataset)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [31]:
# check null values -> no null values -> no management required
full_dataset.isnull().sum()

distance_from_home                0
distance_from_last_transaction    0
ratio_to_median_purchase_price    0
repeat_retailer                   0
used_chip                         0
used_pin_number                   0
online_order                      0
fraud                             0
dtype: int64

In [32]:
# check types of attributes and change them if necessary
# describe types before and after etl
print(full_dataset.dtypes)

# repeat_retailer, ..., fraud are float: before cast them do binary check unique values in these columns
print("unique values for repeat_retailer: ", full_dataset["repeat_retailer"].unique())
print("unique values for used_chip: ", full_dataset["used_chip"].unique())
print("unique values for used_pin_number: ", full_dataset["used_pin_number"].unique())
print("unique values for online_order: ", full_dataset["online_order"].unique())
print("unique values for fraud: ", full_dataset["fraud"].unique())



# all these attributes have as unique values 1 and 0, so we can cast them to binary type
full_dataset['repeat_retailer'] = full_dataset['repeat_retailer'].apply(int)
full_dataset['used_chip'] = full_dataset['used_chip'].apply(int)
full_dataset['used_pin_number'] = full_dataset['used_pin_number'].apply(int)
full_dataset['online_order'] = full_dataset['online_order'].apply(int)
full_dataset['fraud'] = full_dataset['fraud'].apply(int)

print(full_dataset.dtypes)

# check 0 and 1, no more 0. and 1.
print("unique values for repeat_retailer: ", full_dataset["repeat_retailer"].unique())
print("unique values for used_chip: ", full_dataset["used_chip"].unique())
print("unique values for used_pin_number: ", full_dataset["used_pin_number"].unique())
print("unique values for online_order: ", full_dataset["online_order"].unique())
print("unique values for fraud: ", full_dataset["fraud"].unique())

distance_from_home                float64
distance_from_last_transaction    float64
ratio_to_median_purchase_price    float64
repeat_retailer                   float64
used_chip                         float64
used_pin_number                   float64
online_order                      float64
fraud                             float64
dtype: object
unique values for repeat_retailer:  [1. 0.]
unique values for used_chip:  [1. 0.]
unique values for used_pin_number:  [0. 1.]
unique values for online_order:  [0. 1.]
unique values for fraud:  [0. 1.]
distance_from_home                float64
distance_from_last_transaction    float64
ratio_to_median_purchase_price    float64
repeat_retailer                     int64
used_chip                           int64
used_pin_number                     int64
online_order                        int64
fraud                               int64
dtype: object
unique values for repeat_retailer:  [1 0]
unique values for used_chip:  [1 0]
unique values for used_pin_number:  [0 1]
unique values for online_order:  [0 1]
unique values for fraud:  [0 1]

In [40]:
# final dataset after preprocessing
display(full_dataset)

# export dataset in csv
full_dataset.to_csv('card_transdata_preprocessed.csv', index=False)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1,1,0,0,0
1,10.829943,0.175592,1.294219,1,0,0,0,0
2,5.091079,0.805153,0.427715,1,0,0,1,0
3,2.247564,5.600044,0.362663,1,1,0,1,0
4,44.190936,0.566486,2.222767,1,1,0,1,0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0
999996,19.872726,2.683904,2.778303,1,1,0,0,0
999997,2.914857,1.472687,0.218075,1,1,0,1,0
999998,4.258729,0.242023,0.475822,1,0,0,1,0
999999,58.108125,0.318110,0.386920,1,1,0,1,0